"use client";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Contact from "@/components/Contact/Contact";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

// import './css/style.min.css'
// import './css/textRotate.css'
// import './css/select2.min.css'
// import './css/slick.css'
// import './css/jQueryUi.min.css'
import "./js/main";
import "./js/wow.min";
import "./js/lightgallery.min";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <Link rel="preconnect" href="https://fonts.googleapis.com"/>
      <Link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <Link href="https://fonts.googleapis.com/css2?family=Chela+One&display=swap" rel="stylesheet"/>
      <Link href="./fonts/grader-unique-sans-2023-07-13-05-06-32-utc/GraderTTF.ttf" rel="stylesheet"/>

      <Link rel="preconnect" href="https://fonts.googleapis.com"/>
      <Link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <Link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet"/>

      </head>

      <body id="home" className={inter.className}>
        <Navbar />
        <div className="st-height-b80 st-height-lg-b80"></div>
        {children}
        <Contact/>
      </body>
    </html>
  );
}


